# Generated by Django 5.1.4 on 2025-02-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_likes_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
