# Generated by Django 5.1.4 on 2025-04-29 18:55

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_caption_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts/', validators=[posts.models.validate_image_file]),
        ),
    ]
